name: chamados
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.2.0
  flutter: ^3.16.0
dependencies: 
  async: ^2.10.0
  blinking_text: ^1.0.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.3
  data_table_2: ^2.5.7
  dio: ^5.0.3
  dropdown_button2: ^2.3.9
  faker: ^2.1.0
  flex_color_scheme: ^7.3.1
  flutter_typeahead: ^4.3.8
  fluttertoast: ^8.2.2
  get: ^4.6.5
  get_storage: ^2.1.1
  graphite: ^1.1.2
  http: ^1.1.0
  intl: ^0.18.1
  js: ^0.6.5
  mask_text_input_formatter: ^2.4.0
  percent_indicator: ^4.2.3
  pie_chart: ^5.3.2
  shared_preferences: ^2.0.6
  syncfusion_flutter_charts: ^23.1.38
  test_api: ^0.6.0
  validatorless: ^1.2.3
  infinite_scroll_pagination: ^4.0.0
  flutter: 
    sdk: flutter
  flutter_web_plugins: 
    sdk: flutter
  responsive_grid: ^2.4.4
  date_field: ^3.0.5
  file_picker: ^6.1.1
dev_dependencies: 
  flutter_lints: ^3.0.1
  pubspec_dependency_sorter: ^1.0.4
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
